name: CI/CD Pipeline for Task Manager Application

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AZURE_VM_IP: ${{ secrets.AZURE_VM_IP }}
      AZURE_USERNAME: ${{ secrets.AZURE_USERNAME }}
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      REMOTE_APP_DIR: "~/Task_manager_API" # this is the existing application code directory

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: npm install

    # - name: Run tests
    #   run: npm test 

    - name: Deploy new code to Azure VM
      uses: appleboy/scp-action@master
      with:
        host: ${{ env.AZURE_VM_IP }}
        username: ${{ env.AZURE_USERNAME }}
        key: ${{ env.PRIVATE_KEY }}
        source: "."
        target: ${{ env.REMOTE_APP_DIR }}

    - name: SSH and Restart Existing App
      uses: appleboy/ssh-action@master
      with:
        host: ${{ env.AZURE_VM_IP }}
        username: ${{ env.AZURE_USERNAME }}
        key: ${{ env.PRIVATE_KEY }}
        script: |
          cd ${{ env.REMOTE_APP_DIR }}
          pm2 restart app
