name: CI/CD Pipeline for Task Manager Application

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      AZURE_VM_IP: ${{ secrets.AZURE_VM_IP }}
      AZURE_USERNAME: ${{ secrets.AZURE_USERNAME }}
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: npm install

   # - name: Run tests
   #   run: npm test

    - name: Deploy to Azure VM
      uses: appleboy/scp-action@master
      with:
        host: ${{ env.AZURE_VM_IP }}
        username: ${{ env.AZURE_USERNAME }}
        key: ${{ env.PRIVATE_KEY }}
        source: "."
        target: "~/task-manager"

    - name: SSH and Restart App
      uses: appleboy/ssh-action@master
      with:
        host: ${{ env.AZURE_VM_IP }}
        username: ${{ env.AZURE_USERNAME }}
        key: ${{ env.PRIVATE_KEY }}
        script: |
          cd ~/task-manager
          pm2 restart app || pm2 start app.js --name app
